/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class windowjava_Button */

#ifndef _Included_windowjava_Button
#define _Included_windowjava_Button
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     windowjava_Button
 * Method:    createButton
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_windowjava_Button_createButton
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
