/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class windowjava_Component */

#ifndef _Included_windowjava_Component
#define _Included_windowjava_Component
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     windowjava_Component
 * Method:    reshape
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_windowjava_Component_reshape
  (JNIEnv *, jobject, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
