/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class windowjava_Component */

#ifndef _Included_windowjava_Component
#define _Included_windowjava_Component
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     windowjava_Component
 * Method:    CreateWindowClass
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_windowjava_Component_CreateWindowClass
  (JNIEnv *, jclass, jstring);

/*
 * Class:     windowjava_Component
 * Method:    CreateComponent
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_windowjava_Component_CreateComponent
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
