/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class windowjava_Window */

#ifndef _Included_windowjava_Window
#define _Included_windowjava_Window
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     windowjava_Window
 * Method:    createWindow
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_windowjava_Window_createWindow
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
