/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hello_Hello */

#ifndef _Included_hello_Hello
#define _Included_hello_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hello_Hello
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hello_Hello_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
