/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class access_Java */

#ifndef _Included_access_Java
#define _Included_access_Java
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     access_Java
 * Method:    setPrivate
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_access_Java_setPrivate
  (JNIEnv *, jobject, jint);

/*
 * Class:     access_Java
 * Method:    setStaticPrivate
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_access_Java_setStaticPrivate
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
