/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_window4_java_Text */

#ifndef _Included_java_window4_java_Text
#define _Included_java_window4_java_Text
#ifdef __cplusplus
extern "C" {
#endif
#undef java_window4_java_Text_SET_POSITION
#define java_window4_java_Text_SET_POSITION 1L
#undef java_window4_java_Text_SET_SIZE
#define java_window4_java_Text_SET_SIZE 2L
#undef java_window4_java_Text_SET_POSITION_AND_SIZE
#define java_window4_java_Text_SET_POSITION_AND_SIZE 3L
/*
 * Class:     java_window4_java_Text
 * Method:    setNativeText
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_java_1window4_java_Text_setNativeText
  (JNIEnv *, jobject, jstring);

/*
 * Class:     java_window4_java_Text
 * Method:    create
 * Signature: (Ljava_window4/java/Component;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_java_1window4_java_Text_create
  (JNIEnv *, jobject, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
