/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_window4_java_Component */

#ifndef _Included_java_window4_java_Component
#define _Included_java_window4_java_Component
#ifdef __cplusplus
extern "C" {
#endif
#undef java_window4_java_Component_SET_POSITION
#define java_window4_java_Component_SET_POSITION 1L
#undef java_window4_java_Component_SET_SIZE
#define java_window4_java_Component_SET_SIZE 2L
#undef java_window4_java_Component_SET_POSITION_AND_SIZE
#define java_window4_java_Component_SET_POSITION_AND_SIZE 3L
/*
 * Class:     java_window4_java_Component
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_java_1window4_java_Component_destroy
  (JNIEnv *, jobject);

/*
 * Class:     java_window4_java_Component
 * Method:    reshape
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_java_1window4_java_Component_reshape
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     java_window4_java_Component
 * Method:    setBackgroundColor
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_java_1window4_java_Component_setBackgroundColor
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
