/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_window4_java_Text */

#ifndef _Included_java_window4_java_Text
#define _Included_java_window4_java_Text
#ifdef __cplusplus
extern "C" {
#endif
#undef java_window4_java_Text_SET_POSITION
#define java_window4_java_Text_SET_POSITION 1L
#undef java_window4_java_Text_SET_SIZE
#define java_window4_java_Text_SET_SIZE 2L
#undef java_window4_java_Text_SET_POSITION_AND_SIZE
#define java_window4_java_Text_SET_POSITION_AND_SIZE 3L
#undef java_window4_java_Text_SET_FONT_FAMILY
#define java_window4_java_Text_SET_FONT_FAMILY 1L
#undef java_window4_java_Text_SET_FONT_SIZE
#define java_window4_java_Text_SET_FONT_SIZE 2L
#undef java_window4_java_Text_SET_FONT_STRETCH
#define java_window4_java_Text_SET_FONT_STRETCH 4L
#undef java_window4_java_Text_SET_FONT_STYLE
#define java_window4_java_Text_SET_FONT_STYLE 8L
#undef java_window4_java_Text_SET_FONT_WEIGHT
#define java_window4_java_Text_SET_FONT_WEIGHT 16L
#undef java_window4_java_Text_SET_FONT_LINE_HEIGHT
#define java_window4_java_Text_SET_FONT_LINE_HEIGHT 32L
/*
 * Class:     java_window4_java_Text
 * Method:    setNativeText
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_java_1window4_java_Text_setNativeText
  (JNIEnv *, jobject, jstring);

/*
 * Class:     java_window4_java_Text
 * Method:    setTextColor
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_java_1window4_java_Text_setTextColor
  (JNIEnv *, jobject, jint);

/*
 * Class:     java_window4_java_Text
 * Method:    setFont
 * Signature: (Ljava/lang/String;FFIIFIII)V
 */
JNIEXPORT void JNICALL Java_java_1window4_java_Text_setFont
  (JNIEnv *, jobject, jstring, jfloat, jfloat, jint, jint, jfloat, jint, jint, jint);

/*
 * Class:     java_window4_java_Text
 * Method:    setTextHorizontalAlignment
 * Signature: (Ljava_window4/java/TextHorizontalAlignment;)V
 */
JNIEXPORT void JNICALL Java_java_1window4_java_Text_setTextHorizontalAlignment
  (JNIEnv *, jobject, jobject);

/*
 * Class:     java_window4_java_Text
 * Method:    setTextVerticalAlignment
 * Signature: (Ljava_window4/java/TextVerticalAlignment;)V
 */
JNIEXPORT void JNICALL Java_java_1window4_java_Text_setTextVerticalAlignment
  (JNIEnv *, jobject, jobject);

/*
 * Class:     java_window4_java_Text
 * Method:    create
 * Signature: (Ljava_window4/java/Component;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_java_1window4_java_Text_create
  (JNIEnv *, jobject, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
