/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class array_Main */

#ifndef _Included_array_Main
#define _Included_array_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     array_Main
 * Method:    newArray
 * Signature: (I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_array_Main_newArray
  (JNIEnv *, jclass, jint);

/*
 * Class:     array_Main
 * Method:    printArray
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_array_Main_printArray
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
