/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_window2_java_Component */

#ifndef _Included_java_window2_java_Component
#define _Included_java_window2_java_Component
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_window2_java_Component
 * Method:    reshape
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_java_1window2_java_Component_reshape
  (JNIEnv *, jobject, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
