/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_window2_java_Window */

#ifndef _Included_java_window2_java_Window
#define _Included_java_window2_java_Window
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_window2_java_Window
 * Method:    create
 * Signature: (Ljava_window2/java/Component;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_java_1window2_java_Window_create
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     java_window2_java_Window
 * Method:    showWinodw
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_java_1window2_java_Window_showWinodw
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
