/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class exception_Main */

#ifndef _Included_exception_Main
#define _Included_exception_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     exception_Main
 * Method:    nativeThrowException
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_exception_Main_nativeThrowException
  (JNIEnv *, jclass, jstring);

/*
 * Class:     exception_Main
 * Method:    nativeThrowNewException
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_exception_Main_nativeThrowNewException
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
