/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class window_WindowTest */

#ifndef _Included_window_WindowTest
#define _Included_window_WindowTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     window_WindowTest
 * Method:    CreateWindow
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_window_WindowTest_CreateWindow
  (JNIEnv *, jobject, jstring);

/*
 * Class:     window_WindowTest
 * Method:    ShowWindow
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_window_WindowTest_ShowWindow
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
