/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class extend_Main */

#ifndef _Included_extend_Main
#define _Included_extend_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     extend_Main
 * Method:    nativeHello
 * Signature: (Lextend/Super;)V
 */
JNIEXPORT void JNICALL Java_extend_Main_nativeHello
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
