/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_window3_java_Button */

#ifndef _Included_java_window3_java_Button
#define _Included_java_window3_java_Button
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_window3_java_Button
 * Method:    create
 * Signature: (Ljava_window3/java/Component;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_java_1window3_java_Button_create
  (JNIEnv *, jobject, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
