/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_window3_java_Component */

#ifndef _Included_java_window3_java_Component
#define _Included_java_window3_java_Component
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_window3_java_Component
 * Method:    reshape
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_java_1window3_java_Component_reshape
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
